name: chinaculture
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: 3.0.9
  flutter_spinkit: 4.1.2
  url_launcher: 5.4.2
  fluro: 1.6.1
  provider: 4.0.4
  provider_architecture: 1.0.5
  flutter_platform_widgets: 0.32.5
  shared_preferences: 0.5.3
  path_provider: 1.6.5
  rxdart: 0.23.1
  oktoast: 2.3.1
  flutter_swiper: 1.1.6
  connectivity: 0.4.8+1
  built_value: 7.0.4
  get_it: 3.1.0
  hive: 1.4.1+1
  device_info: 0.4.2+1
  shimmer: 1.1.1
  fijkplayer: 0.7.0
  flutter_bluetooth_basic: 0.1.3
  barcode_scan: 2.0.1
  web_socket_channel: 1.1.0
  flushbar: 1.9.1
  flare_flutter: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # mock data
  mockito: ^4.1.1
  build_runner: ^1.7.2
  json_serializable: ^3.2.0
  built_value_generator: ^7.0.4
  hive_generator: ^0.7.0
  pedantic: ^1.8.0
  logger: ^0.8.3


flutter:
  uses-material-design: true
  assets:
    - assets/ifredom.jpg
    - assets/image/
    - assets/image/custom/
    - assets/image/ador/
  
  fonts:
    - family: myIcons
      fonts:
        - asset: assets/fonts/iconfont.ttf
          style: italic
          weight: 400
